Telas 09 e 10 feitas com dados mockup
AIC3BancodoTempo/banco_tempo_app pull request #12
Opened 2020-12-08 20:58 UTC by kevinppaulo

2020-12-08 22:47 UTC, JuniorZilles commented on lib/screens/my_posts/core/PostCard.dart
> +                      return Column(
eu recomendaria colocar o conteudo desse column em um outro arquivo, pois esse arquivo ficou muito grande do jeito que tá

2020-12-08 22:48 UTC, JuniorZilles commented on lib/screens/my_posts/core/PostCard.dart
> +                      return Row(
o mesmo que o comentário anterior, quando separado fica mais fácil saber onde mexer

2020-12-08 22:57 UTC, JuniorZilles requested changes
O código em si está bom, não aplicou o block pattern, mas dá pra fazer mais tarde, só o arquivo PostCard tá no local errado ele ficaria dentro da pasta, core mas na pasta fora da pasta my_posts, quanto ao nome o padrão recomendado é usar o underscore a exemplo MyPost ficaria my_post_screen

2021-03-02 14:29 UTC, JoelsonSartoriJr requested changes
Arquivo MyPosts e PendingPosts não são iguais ? qual a diferença os dados ? se for não faz sentido ter duas classes

2021-03-16 19:33 UTC, closed without merging