Telas 5 e 6
AIC3BancodoTempo/banco_tempo_app pull request #14
Opened 2021-02-08 11:52 UTC by jardeldargas

2021-02-08 12:21 UTC, JoelsonSartoriJr commented
Tenho alguns pontos então vou deixar como lista aqui ^^(qualquer coisa estou a disposição).

- [ ] Componentizar o código, um exemplo é o componente "image_carousel", poderia ser uma classe dentro de screens/core
- [ ] Adicionar no .gitignore coisas que nao deveriam subir exempo é .vscode
- [ ] E algumas coisas achei meio confuso exemplo o "spaceHorizontal", não seria mais facil colocar isso no componente ou direto na tela ? (ai tambem posso ta falando m porem achei meio estranho )^^

2021-02-08 23:26 UTC, JuniorZilles requested changes
Itens a alterar

- [ ] nomenclatura das telas e arquivos
- [ ] componetização de campos

2021-02-08 23:26 UTC, JuniorZilles commented on pubspec.yaml
> +  simple_animations: ^1.3.3
é uma dependência de desenvolvimento apenas?

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_5.dart
> +import 'package:flutter/material.dart';
trocar o nome da tela, não faz sentido se utilizar essa nomenclatura, pois tu fica obrigado a sempre a acessar o figma pra saber que tela é essa, tenta usar uma ou mais palavras que expressem o seu objetivo.

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_5.dart
> +  Widget image_carousel() {
colocar essa função como um componente recebendo os parâmetros necessários

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_5.dart
> +  Widget title() {
mesmo comentário do anterior

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_5.dart
> +  Widget description_title() {
idem

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_5.dart
> +  Widget description() {
idem

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_5.dart
> +  Widget chips() {
idem

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_5.dart
> +  Widget anunciante() {
idem

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_5.dart
> +  Widget product_button_message() {
idem

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_5.dart
> +  Widget spaceVertical(double size) {
se essa função for utilizada em mais telas passar pra dentro de core

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_5.dart
> +  Widget spaceHorizontal(double size) {
mesmo do anterior

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_5.dart
> +class ColorTicker extends StatelessWidget {
colocar em um arquivo separado e renomear de uma forma mais autoexplicativa

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_6.dart
> +import 'package:flutter/material.dart';
mesmo esquema na questão do nome e o nome da classe tbm

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_6.dart
> +                      child: TextFormField(
os campos de texto podem virar componente, aplicar nos demais a baixo

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_6.dart
> +                Wrap(
transforma em componente, se quiser pode já anexar o image_picker para obter as imagens, o que vai ter que ser adicionado as opções de galeria e câmera

2021-02-08 23:26 UTC, JuniorZilles commented on lib/screens/tela_5_6/tela_6.dart
> +                Padding(
o botão pode virar um componente e pode ser colocado na pasta core pra ser reutilizado em outras telas

2021-02-08 23:26 UTC, JuniorZilles commented on .vscode/launch.json
> +{
cara acho que esse arquivo não devia ter vindo junto, dá uma olhada se o .git_ignore tem essa pasta adicionada

2021-02-09 01:27 UTC, jardeldargas commented on pubspec.yaml
> +  simple_animations: ^1.3.3
dependência removida

2021-02-09 01:28 UTC, jardeldargas commented on lib/screens/tela_5_6/tela_6.dart
> +                Wrap(
Por enquanto só importei a package.

2021-02-09 01:28 UTC, jardeldargas commented on .vscode/launch.json
> +{
veja se tá ok agora

2021-02-09 01:29 UTC, closed without merging