Feature/cadastro e card description
AIC3BancodoTempo/banco_tempo_app pull request #15
Opened 2021-02-09 01:31 UTC by jardeldargas

2021-02-09 12:02 UTC, JuniorZilles commented on .gitignore
adicionar `.vscode/ ` no .gitignore

2021-02-09 12:28 UTC, JuniorZilles requested changes
Pontos a considerar:

- observar que quando falamos em componentes a parte selecionada deve se tornar um statelesswidget;
- quanto a questão das pastas, como são duas telas são duas pastas separadas, e observar que quando um componente é usado mais de uma vez por outras telas ele vai para a pasta core

2021-02-09 12:28 UTC, JuniorZilles commented on lib/screens/cadastros_e_descricaoCard/components/fields.dart
> +        child: TextFormField(
transformar em componente o textformfield

2021-02-09 12:28 UTC, JuniorZilles commented on pubspec.yaml
> +    sdk: flutter
ver aqui, parece que sumiu  o import equatable: ^1.2.5

2021-02-09 12:28 UTC, JuniorZilles commented on lib/screens/core/button.dart
> +import 'package:flutter/material.dart';
lembra que é pra tornar ele um componente, daí a ideia é criar um statelesswidget, usa como exemplo o que fiz no nosso app

2021-02-09 12:28 UTC, JuniorZilles commented on lib/screens/cadastros_e_descricaoCard/descricao_card.dart
> +class MyHomePage extends StatefulWidget {
o nome da classe tem que trocar tbm

2021-02-09 12:28 UTC, JuniorZilles commented on lib/screens/cadastros_e_descricaoCard/components/fields.dart
> +Widget photoInclude() {
cria outro arquivo e cria um statelesswidget passando tudo que é variável usar exemplo do nosso app

2021-02-09 12:28 UTC, JuniorZilles commented on lib/screens/cadastros_e_descricaoCard/components/fields.dart
> +import 'package:flutter/material.dart';
todas as funções que tão aqui podem virar um arquivo separado devidamente identificados

2021-02-09 12:28 UTC, JuniorZilles commented on lib/screens/cadastros_e_descricaoCard/cadastro_habilidade.dart
> +class MyCustomForm extends StatefulWidget {
trocar o nome pra condizer com o do arquivo

2021-02-09 12:28 UTC, JuniorZilles commented on lib/main.dart
> +import 'package:banco_do_tempo_app/screens/cadastros_e_descricaoCard/descricao_card.dart';
provavelmente tem conflitos para fazer o merge então prioriza o conteúdo que já tá lá para esse arquivo quando resolver eles, no final esse arquivo vai mudar

2021-02-10 12:16 UTC, JoelsonSartoriJr requested changes
No geral tenta sempre pensar nos componentes como caixinhas em que cada coisa fica separada, já que esse foi o principal problema do código, botão, form, input, tudo que for estilizado e pode ser reutilizado transforma em componentes com nomes explicativos em arquivos separados

2021-02-10 12:16 UTC, JoelsonSartoriJr commented on lib/screens/cadastros_e_descricaoCard/cadastro_habilidade.dart
> +class MyCustomForm extends StatefulWidget {
è bom lembrar que o nome deve ser auto explicativo, um exemplo bom para em um card que sera o mesmo para varias noticias , ao invez do nome ser "MyCustomCard" é mais interessante ser "CardNoticia"

2021-02-10 12:16 UTC, JoelsonSartoriJr commented on lib/screens/cadastros_e_descricaoCard/components/fields.dart
> +        child: TextFormField(
Muitos elementos que podem ser transformado em camponentes para deixar o código mais legivel e reutilizavel, e cada um em um arquivo, assim a leitura do componente tambem se torna simples

2021-02-22 18:27 UTC, jardeldargas commented on lib/screens/cadastros_e_descricaoCard/components/fields.dart
> +        child: TextFormField(
Ver se está ok agora.

2021-02-22 18:27 UTC, jardeldargas commented on pubspec.yaml
> +    sdk: flutter
Ajustado.

2021-02-22 18:29 UTC, jardeldargas commented on lib/screens/core/button.dart
> +import 'package:flutter/material.dart';
Fiquei com uma dúvida nisso. Se eu criar o stlw, não entendi o que devo incluir dentro do stlw. Ficou por enquanto só o widget criado deste botão.

2021-02-22 18:29 UTC, jardeldargas commented on lib/screens/cadastros_e_descricaoCard/descricao_card.dart
> +class MyHomePage extends StatefulWidget {
Veja se está ok agora.

2021-02-22 18:29 UTC, jardeldargas commented on lib/screens/cadastros_e_descricaoCard/components/fields.dart
> +Widget photoInclude() {
Veja se está ok agora.

2021-02-22 18:29 UTC, jardeldargas commented on lib/screens/cadastros_e_descricaoCard/components/fields.dart
> +import 'package:flutter/material.dart';
Veja se está ok agora.

2021-02-22 18:29 UTC, jardeldargas commented on lib/screens/cadastros_e_descricaoCard/cadastro_habilidade.dart
> +class MyCustomForm extends StatefulWidget {
Vejam se está ok agora.

2021-02-22 18:30 UTC, jardeldargas commented on lib/main.dart
> +import 'package:banco_do_tempo_app/screens/cadastros_e_descricaoCard/descricao_card.dart';
ok

2021-02-22 19:12 UTC, JoelsonSartoriJr requested changes
Reintero as modificações informadas pelo @JuniorZilles

2021-02-22 19:12 UTC, JoelsonSartoriJr commented on lib/main.dart
> +      home: AddAbilityPage(),
Portugues ou em ingles ? kkkkkk

2021-02-22 19:12 UTC, JoelsonSartoriJr commented on lib/screens/core/main_button.dart
> +}
Seria interessante tambem o botão receber a função, e ter um nome mais intendivel

2021-02-22 19:15 UTC, JuniorZilles requested changes
Segue os pontos apontados q fica ok

2021-02-22 19:15 UTC, JuniorZilles commented on lib/screens/descricaoHabilidade/components/carousel_image.dart
> +Widget image_carousel(carouselImgs1, carouselImgs2) {
mesma coisa só o parâmetro de entrada pode ser uma lista já, daí não precisa montar dentro desse widget

2021-02-22 19:15 UTC, JuniorZilles commented on lib/screens/descricaoHabilidade/components/chips.dart
> +Widget chips() {
mesma coisa

2021-02-22 19:15 UTC, JuniorZilles commented on lib/screens/descricaoHabilidade/components/description_under_title.dart
> +Widget description() {
esse aqui não precisa virar componente, é só um texto

2021-02-22 19:15 UTC, JuniorZilles commented on lib/screens/descricaoHabilidade/components/main_description_title.dart
> +  return Container(
transformar em statelesswidget

2021-02-22 19:15 UTC, JuniorZilles commented on lib/screens/descricaoHabilidade/components/title_in_description.dart
> +Widget description_title() {
mesmo anterio

2021-02-22 23:34 UTC, jardeldargas commented on ios/Runner/Info.plist
> +	<string>Allow access to microphone</string>
pelo que vi, não.

2021-02-22 23:35 UTC, jardeldargas commented on lib/screens/cadastrosHabilidades/components/insert_input_texts.dart
> +Widget insertInputs(insertLabel) {
ajustado.

2021-02-22 23:35 UTC, jardeldargas commented on lib/screens/cadastrosHabilidades/components/title_add_text.dart
> +Widget titleAddText(insertTitleHere) {
ajustado.

2021-02-22 23:36 UTC, jardeldargas commented on lib/screens/core/appBar.dart
> +Widget buildAppBar(insertText) {
o app bar não teve como referenciar para o arquivo separado. Por isso inclui direto no código onde eu chamaria a função.

2021-02-22 23:37 UTC, jardeldargas commented on lib/screens/descricaoHabilidade/components/carousel_image.dart
> +Widget image_carousel(carouselImgs1, carouselImgs2) {
ver no backend.

2021-02-22 23:37 UTC, jardeldargas commented on lib/screens/descricaoHabilidade/components/chips.dart
> +Widget chips() {
ajustado.

2021-02-22 23:37 UTC, jardeldargas commented on lib/screens/descricaoHabilidade/components/description_under_title.dart
> +Widget description() {
ajustado.

2021-02-22 23:37 UTC, jardeldargas commented on lib/screens/descricaoHabilidade/components/main_description_title.dart
> +  return Container(
ajustado.

2021-02-22 23:37 UTC, jardeldargas commented on lib/screens/descricaoHabilidade/components/title_in_description.dart
> +Widget description_title() {
ajustado.

2021-02-28 22:06 UTC, matheusscheu approved these changes

2021-02-28 22:19 UTC, closed without merging