Feature/login
AIC3BancodoTempo/banco_tempo_app pull request #16
Opened 2021-02-09 18:30 UTC by matheusscheu

2021-02-09 18:34 UTC, JuniorZilles commented on assets/icons/google-plus.svg
> +</g>
será que não dá pra tirar essas aberturas <g></g> das linhas 17 até 46?

2021-02-09 19:26 UTC, JuniorZilles requested changes
- o esquema de o arquivo principal chamar um body e daí tem um background recebendo o conteúdo ficou meio ruim de ler o código;
- se o background é o mesmo para as três telas tu pode colocar na pasta core e a chamada coloca dentro do arquivo principal da tela;
- o esquema de componetização levar em conta os positioned e os campos de texto, que podem ser reutilizados.
- a não esquece que as pastas e arquivos é tudo com letra minúscula, vi que tu criou as pastas com letra maiúscula no inicio

2021-02-09 19:26 UTC, JuniorZilles commented on lib/screens/Welcome/components/background.dart
> +          Positioned(
esses positioned podem virar um componente

2021-02-09 19:26 UTC, JuniorZilles commented on lib/screens/Welcome/welcome_screen.dart
> +import 'package:flutter/material.dart';
não sei, não gostei muito dessa estrutura, o conteúdo do background podia já tá aqui dentro

2021-02-09 19:26 UTC, JuniorZilles commented on lib/screens/Welcome/components/body.dart
> +            RoundedButton(
botão pode virar component tbm

2021-02-09 19:26 UTC, JuniorZilles commented on lib/screens/Signup/components/background.dart
> +          Positioned(
transforma em componente, observa que tu usou um positioned tbm no welcome

2021-02-09 19:26 UTC, JuniorZilles commented on lib/main.dart
>  import 'package:flutter/material.dart';
esse arquivo eu diria pra tu reverter para o original

2021-02-09 19:26 UTC, JuniorZilles commented on lib/screens/Login/components/background.dart
> +          Positioned(
virar componente e colocar na pasta core, substituir nos outros tbm

2021-02-10 12:07 UTC, JoelsonSartoriJr requested changes
Não consegui observar nenhuma mudança que já não foi comentada pelo junior, é sempre bom pensar no que seria possivel reaproveitar se alguma coisa parece ser muito igual quer dizer que da para usar o mesmo componente( se a diferença for texto ou cor é possivel passar sempre como parametros).

2021-02-10 18:59 UTC, matheusscheu commented on assets/icons/google-plus.svg
> +</g>
eu retirei as svgs que eu tinha esquecido

2021-02-10 19:00 UTC, matheusscheu commented on lib/components/rounded_input_email.dart
> +import 'package:banco_do_tempo_app/components/text_field_container.dart';
possui um icone diferente apenas, devo juntar ambos e passar o ícone?

2021-02-11 10:35 UTC, JoelsonSartoriJr approved these changes
Parece está tudo ok.

2021-02-11 10:45 UTC, JuniorZilles commented on lib/components/rounded_input_email.dart
> +import 'package:banco_do_tempo_app/components/text_field_container.dart';
sim

2021-02-11 10:49 UTC, JuniorZilles approved these changes
tá ok agora

2021-02-11 14:01 UTC, jardeldargas approved these changes

2021-02-11 14:01 UTC, merged