Tela serviços/habilidades
AIC3BancodoTempo/banco_tempo_app pull request #17
Opened 2021-02-10 04:11 UTC by LeoMoraes32

commit

2021-02-11 11:08 UTC, JuniorZilles requested changes
pontos a observar

- [ ] componetização de botões e cards;
- [ ] remover código que não é utilizado;
- [ ] ajustar o nome da classe para ficar de acordo com o arquivo e seu objetivo.

2021-02-11 11:08 UTC, JuniorZilles commented on lib/servicos.dart
> +final GlobalKey<ScaffoldState> scaffoldKey = GlobalKey<ScaffoldState>();
essas duas linhas podem ir para o widget de baixo, falo das linhas com as variáveis snackBar e scaffoldKey

2021-02-11 11:08 UTC, JuniorZilles commented on lib/servicos.dart
> +class MyStatelessWidget extends StatelessWidget {
o nome deve ser conciso e compreensível, estando de acordo com a sua devida tela

2021-02-11 11:08 UTC, JuniorZilles commented on lib/servicos.dart
> +          Card(
os cards podem virar um componente recebendo um model contendo os atributos necessários

2021-02-11 11:08 UTC, JuniorZilles commented on lib/servicos.dart
> +      drawer: Drawer(
o drawer pode virar um componente tbm, daí vai para um arquivo separado

2021-02-11 11:08 UTC, JuniorZilles commented on lib/servicos.dart
> +      floatingActionButton: FloatingActionButton(
esse botão vai ser usado em outras telas, por que daí pode virar um componente tbm

2021-02-11 12:01 UTC, JoelsonSartoriJr requested changes
Reforço os pontos que o @JuniorZilles informou, olhar um pouco a documentação do padrão de projeto que decidimos utilizar, é bom lembrar que o código deve ser igual a um texto ou seja, deve ser facil de ler, fazer sentido o nome das "coisas" (ou seja as funções devem ter o nome do que elas são).

2021-02-11 14:20 UTC, matheusscheu requested changes
não encontrei nada alem do que o junior ja citou para ser alterado.

2021-02-28 23:40 UTC, matheusscheu requested changes
o junior ja citou os pontos necessários

2021-03-09 12:46 UTC, matheusscheu commented
Por favor, assim que possivel da uma atenção as mudanças propostas

2021-03-18 22:15 UTC, closed without merging