Services
AIC3BancodoTempo/banco_tempo_app pull request #24
Opened 2021-03-17 15:29 UTC by CassianoSS

2021-03-17 16:21 UTC, JoelsonSartoriJr submitted a review, later dismissed

2021-03-18 23:13 UTC, matheusscheu requested changes
Somente alterar a Main

2021-03-18 23:13 UTC, matheusscheu commented on lib/main.dart
>  import 'package:flutter/material.dart';
copiar as informações corretas das Main, pois se subir assim algumas coisas das rotas que foram feitas se perderá

2021-03-20 16:57 UTC, JuniorZilles approved these changes

2021-03-20 16:59 UTC, merged