Botão de acesso ao termos e condições
AIC3BancodoTempo/banco_tempo_app pull request #41
Opened 2021-03-27 03:12 UTC by matheusscheu

2021-03-27 16:33 UTC, JuniorZilles requested changes
te prepara pros conflitos, e o botão podia ser um componente

2021-03-27 16:33 UTC, JuniorZilles commented on lib/screens/register_questionary/questionary_screen.dart
> +              TextButton(
pode ser componente

2021-03-27 16:33 UTC, JuniorZilles commented on lib/screens/register_questionary/questionary_screen.dart
> +                    final showSnackBar = ScaffoldMessenger.of(context)
só avisando vai dar conflito com a develop

2021-03-27 16:57 UTC, CassianoSS commented
Esse código da resgister_questionary screen está desatualizado, esses problemas já foram corrigidos. O código foi corrigido quando fiz a pr a um tempo atrás.

https://github.com/CassianoSS/banco_tempo_app/blob/nova_tela/lib/screens/resgister_questionary/custom_register_questionary_screen.dart

2021-03-27 20:51 UTC, CassianoSS approved these changes

2021-03-27 20:52 UTC, CassianoSS approved these changes

2021-03-27 20:52 UTC, CassianoSS approved these changes

2021-03-27 20:52 UTC, CassianoSS approved these changes

2021-03-27 20:54 UTC, CassianoSS approved these changes

2021-03-29 16:49 UTC, JuniorZilles approved these changes

2021-03-29 16:49 UTC, merged