Dropdown
AIC3BancodoTempo/banco_tempo_app pull request #43
Opened 2021-03-29 20:21 UTC by CassianoSS

Substituí os TextFormFields por DropdownButtonFormField e deixar dentro do que está previsto no Figma. 

Mas tem bastante coisa faltando, eu não consegui deixar os campos 'componentizados' pq eu não consegui achar uma maneira de fazer isso dar certo com um StatefulWidget e com isso eu tbm não consegui achar um jeito de popular esses dropdowns com dados e um json.

2021-03-29 21:10 UTC, JuniorZilles requested changes
atentar quando for mexer pegar o conteúdo da develop, pra não acabar removendo coisas

2021-03-29 21:10 UTC, JuniorZilles commented on lib/screens/register_questionary/questionary_screen.dart
>                              SnackBar(content: Text('Analisando respostas...')));
tua alteração tirou isso do botão
authBloc.add(SignupEvent());

2021-03-30 10:45 UTC, matheusscheu requested changes
Somente a alteração ja solicitada pelo junior

2021-03-30 11:57 UTC, jardeldargas requested changes
Incluir novamente o authBloc.add(SignupEvent()) - mesma coisa que o Junior apontou

2021-03-30 17:23 UTC, JuniorZilles approved these changes
ok

2021-03-30 17:56 UTC, merged